

export const SCREENS_EMPRESAS = {

    GENERAL : 1,
    RODALES_RESUMEN: 2,
    SAGPYAS_RESUMEN: 3,
    PRODUCCION_RESUMEN: 4,
    COSTOS_RESUMEN: 5
}


export const SCREENS_RODALES = {
    GENERAL: 1,
    PLANIFICACION_INTERVENCIONES: 2
}